# -*- coding: utf-8 -*-
"""27 may, setter ,getter, encapsulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10oWMHn3oKmVjt_pLTH64jzeUlSHyzqXY
"""

#encapsulation-> is an important piller of oops in which
#we bind the data into one unit...so that the access on the
#attrubutes should be restricted

#in pyhton, access modifiers
# public is accesable from everywhere the default in python
#2. protected(_(sinlge under score))-> suggests the member is internal and
#should only be used within the class and its subclasses

#3. (__(double under score))-> triggers name mangling, making it harder(but not impossible)
#to access from outside the class

#name mangling in python-> it is a machenism that prevents accidental name conflicts
#between attributes of a clas and its subclass, it is ofter mistaken for a way
#to create 'private' variables. but its primary propose is to ensure that internal class
#attrubutes are not unintentionally overridden during inheritence

#setter is mthod through which we set the new values of private and protected
#attributes
bankAccount:
  def __init__(self,name,amount,pin):
    self.name=name
    self._balance=amount #protected attribute
    self.__pin=pin #private attribute

  def change_pin(self,new_pin):
    self.__pin=new_pin
    print('pin changed succefully')

  acc=bankAccount('ram',30000,1234)

class bankAccount:
  def __init__(self,name,amount,pin):
    self.name=name
    self._balance=amount #protected attribute
    self.__pin=pin #private attribute

  def change_pin(self,new_pin):
    self.__pin=new_pin
    print('pin changed succefully')

  def check_balance(self):
    print('current balance: ',self._balance)

  def deposit(self,new_amount):
    self._balance=self._balance+new_amount
    print('updated amount: ',self._balance)

  def withdraw(self,pin,amount):
    if self.__pin==pin:
      if self._balance>=amount:
        self._balance=self._balance-amount
        print('current balance: ',self._balance)
      else:
        print('insufficient amount')
    else:
     print('enter correct pin')

acc=bankAccount('ram',30000,1234)
acc.deposit(5000)
acc.withdraw(1238,10000)

