# -*- coding: utf-8 -*-
"""29 may,assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYTrCeAC-a8SBRo3K7jm44bJ9ubL7E2H
"""

class BankAccount:
  def __init__(self,balance,name):
    self.name=name
    self.__balance=balance

  def deposit(self,amount):
    self.__balance=self.__balance+amount
    print('after deposit balance: ',self.__balance)

  def withdraw(self,amount):
    if amount<=self.__balance:
      self.__balance-=amount
      print('withdrawn: ', amount)
      print('balance after withdrawn: ',self.__balance)

  def get_balance(self):
    return self.__balance

  def calculate_interest(self):
    pass

class CurrentAccount(BankAccount):
  def calculate_interest(self):
    interest=self.get_balance()*0.02
    print('current account interest: ',interest)


class SavingsAccount(BankAccount):
  def calculate_interest(self):
    interest=self.get_balance()*0.05
    print('saving account interest: ',interest)

s=SavingsAccount(15000,'ram')
c=CurrentAccount(20000,'shyam')

s.deposit(2000)
s.withdraw(3000)
print("Balance:", s.get_balance())
s.calculate_interest()

c.deposit(5000)
c.withdraw(10000)
print("Balance:", c.get_balance())
c.calculate_interest()

class ride:
  def __init__(self,name):
    self.name=name

  def book_ride(self):
    print(f'{self.name} has booked a ride successfully')

  def calculate_fare(self,distance):
    pass

class BikeRide(ride):
  def calculate_fare(self,distance):
    fare=distance*10
    print(f'bike ride fare for{distance} km: {fare}')

class AutoRide(ride):
  def calculate_fare(self,distance):
    fare=distance*20
    print(f'auto ride fare for{distance} km: {fare}')

class CabRide(ride):
  def calculate_fare(self,distance):
    fare=distance*25
    print(f'Cab ride fare for{distance} km: {fare}')

bike=BikeRide('bike')
auto=AutoRide('auto')
cab=CabRide('cab')

bike.book_ride()
bike.calculate_fare(5)

auto.book_ride()
auto.calculate_fare(5)

cab.book_ride()
cab.calculate_fare(5)

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def show_details(self):
        print("Name:", self.name)
        print("Age:", self.age)


class Employee(Person):
    def __init__(self, name, age, salary):
        super().__init__(name, age)
        self.__salary = salary

    def get_salary(self):
        return self.__salary

    def show_details(self):
        super().show_details()
        print("Salary:", self.__salary)



class Manager(Employee):
    def __init__(self, name, age, salary):
        super().__init__(name, age, salary)

    def approve_leave(self, employee_name):
        print(f"Manager approved leave for {employee_name}")

    def view_employee_details(self, employee):
        print("\n Employee Details ")
        employee.show_details()

    def calculate_yearly_bonus(self):
        bonus = self.get_salary() * 0.20   # 20%
        print("Yearly Bonus:", bonus)


emp = Employee("Rahul", 25, 30000)
mgr = Manager("Amit", 40, 80000)

mgr.view_employee_details(emp)
mgr.approve_leave(emp.name)
mgr.calculate_yearly_bonus()

#6.